// Cloudflare Worker：YouTube 逐字稿中繼站
//
// 用途：純前端 PWA 因瀏覽器 CORS 限制無法直接讀取 YouTube 頁面，
// 這支 Worker 在伺服器端（不受 CORS 限制）代為抓取字幕並整理成 JSON 回傳給 App。
//
// 部署方式見 README.md「Cloudflare Worker 部署步驟」。
// 使用方式：GET https://你的worker網址.workers.dev/?v=YOUTUBE_VIDEO_ID

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS'
};

function jsonResponse(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json; charset=utf-8' }
  });
}

export default {
  async fetch(request) {
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: CORS_HEADERS });
    }

    const url = new URL(request.url);
    const videoId = url.searchParams.get('v');
    if (!videoId) {
      return jsonResponse({ error: '缺少 v 參數（YouTube 影片 ID）' }, 400);
    }

    try {
      // 1. 伺服器端抓取 watch 頁面（沒有瀏覽器 CORS 限制）
      const watchRes = await fetch(`https://www.youtube.com/watch?v=${videoId}&hl=en`, {
        headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' }
      });
      if (!watchRes.ok) {
        return jsonResponse({ error: '無法取得影片頁面，請確認影片網址是否正確' }, 502);
      }
      const html = await watchRes.text();

      // 2. 從內嵌的 JSON 資料中找出字幕軌清單
      const match = html.match(/"captionTracks":(\[[^\]]*\])/);
      if (!match) {
        return jsonResponse({ error: '此影片沒有可用的字幕，請改用手動貼上逐字稿' }, 404);
      }

      let tracks;
      try {
        tracks = JSON.parse(match[1].replace(/\\u0026/g, '&'));
      } catch (e) {
        return jsonResponse({ error: '字幕軌資料解析失敗' }, 500);
      }

      // 3. 選字幕軌優先順序：手動英文字幕 > 自動英文字幕 > 任一語言
      const track =
        tracks.find((t) => t.languageCode === 'en' && t.kind !== 'asr') ||
        tracks.find((t) => t.languageCode === 'en') ||
        tracks[0];

      if (!track || !track.baseUrl) {
        return jsonResponse({ error: '找不到可用的字幕軌' }, 404);
      }

      // 4. 抓取結構化字幕（json3 格式，含每段文字與時間戳）
      const capRes = await fetch(`${track.baseUrl}&fmt=json3`);
      if (!capRes.ok) {
        return jsonResponse({ error: '字幕內容下載失敗' }, 502);
      }
      const capJson = await capRes.json();

      const segments = (capJson.events || [])
        .filter((e) => e.segs && e.segs.length)
        .map((e) => ({
          start: Math.round((e.tStartMs || 0)) / 1000,
          text: e.segs.map((s) => s.utf8 || '').join('').replace(/\n/g, ' ').trim()
        }))
        .filter((s) => s.text);

      return jsonResponse({
        videoId,
        lang: track.languageCode,
        isAutoGenerated: track.kind === 'asr',
        segments
      });
    } catch (e) {
      return jsonResponse({ error: `抓取逐字稿時發生錯誤：${e.message || e}` }, 500);
    }
  }
};
